### PR TITLE
Make an attempt at counting exposure for BNB- or NuMI-triggered data

### PR DESCRIPTION
**Pull request by cjbackhouse**
Based on what I learned in the meeting today. Does this 1) look sane? @jzennamo and 2) do something reasonable seeming on the current samples? @brucehoward-physics

I made this PR against the production branch because a develop version of this would have to leave out the NuMI part for now. Is it worth incrementally merging the production branch back to develop, rather than waiting for some idealized moment when it is "finished"?

### CODE REVIEW

**Comment by jzennamo** [comment]
Looks good to me, has this been tested in data and MC? How does this behave for offbeam? For offbeam the number of spills will be tracked in the data product

**Comment by jzennamo** [comment]
Looks good to me, has this been tested in data and MC? How does this behave for offbeam? For offbeam the number of spills will be tracked in the data product

**Review by jzennamo — APPROVED** [review]

**Comment by cjbackhouse** [comment]
@jzennamo I assume we would still get zero here for offbeam, which is the status quo. Once there is a suitable field somewhere we can use it, but I understand that's not currently possible.
Last I heard @brucehoward-physics was having some trouble running this. I'm happy to hear it looks sane, but I'd kind of like it to be confirmed to give a sane answer in practice too.

**Comment by brucehoward-physics** [comment]
There was more follow-up in "private" on this - the issue was that it ran for flat CAFs but not unflattened CAFs. @cjbackhouse made a new version of SRProxy addressing this - I guess this may be in another PR(?)

Anyway, I now see something sensible in some quick looking, so I can hit approve.

**Review by brucehoward-physics — APPROVED** [review]

**Comment by cjbackhouse** [comment]
> @cjbackhouse made a new version of SRProxy addressing this - I guess this may be in another PR(?)

https://github.com/SBNSoftware/sbnanaobj/pull/59 https://github.com/SBNSoftware/sbnana/pull/68

**Pull request merged**
