### PR TITLE
Adjust makefiles to find sbnanaobj whether it's part of the mrb area or provided as an external product.

### PR DESCRIPTION
**Pull request by cjbackhouse**

### CODE REVIEW

**Review by wesketchum — COMMENTED** [review]
It builds standalone.

Does it work if you make a change on sbnanaobj _and_ sbnana (e.g. add something to standard record in both?). Would be good to verify that as a minor test.

**Comment by cjbackhouse** [comment]
If I add a field in StandardRecord various code rebuilds, but not the proxy files don't regenerate. Apparently the DEPENDS line isn't working, but I'm not expert enough at cmake to figure out exactly why. When this was all in sbncode, using SBNCODE_DIR for this purpose, it did all work.

**Comment by ikatza** [comment]
I believe this is the right place to report this. 

I'm trying to build `sbncode` along with `sbndcode` version `v9_15_00` and I'm getting a bunch of errors like this one:

```
/sbnd/app/users/icaza/work/sbncode/srcs/sbncode/sbncode/CAFMaker/FillReco.h:32:10: fatal error: sbnanaobj/StandardRecord/SRSlice.h: No such file or directory
 #include "sbnanaobj/StandardRecord/SRSlice.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

These are the relevant setups I have:
```
sbnanaobj         v09_15_00       -f Linux64bit+3.10-2.17 -q e19:prof        -z /cvmfs/sbnd.opensciencegrid.org/products/sbnd
sbndaq_artdaq_core  v0_07_03_of0    -f Linux64bit+3.10-2.17 -q e19:prof        -z /cvmfs/sbnd.opensciencegrid.org/products/sbnd
sbnobj            v09_10_00       -f Linux64bit+3.10-2.17 -q e19:prof        -z /cvmfs/sbnd.opensciencegrid.org/products/sbnd
```

The necessary shared objects are there:
```
ls /cvmfs/sbn.opensciencegrid.org/products/sbn/sbnanaobj/v09_15_00/slf7.x86_64.e19.prof/lib/
libStandardRecord_dict.so*  libStandardRecord.so*  sbnanaobj/
```

but somehow not reachable? I suspect because the names are wrong. 

I for one much prefer having longer names that show the whole path. That way is much easier to find and debug code, like right now. I've cloned `sbnanaobj` and made a number of changes to rename those shared objects so that they look like:
```
ls localProducts_larsoft_v09_15_00_e19_prof/sbnanaobj/v09_15_00/slf7.x86_64.e19.prof/lib/
libsbnanaobj_StandardRecord_dict.so*  libsbnanaobj_StandardRecord.so*  sbnanaobj/
```

I can now locally build.

**Comment by ikatza** [comment]
I've opened these two:
https://github.com/SBNSoftware/sbnanaobj/pull/1
https://github.com/SBNSoftware/sbncode/pull/80

**Comment by cjbackhouse** [comment]
I have no particular problem with making the library names fully qualified, though note that there might be changes required in CAFAna runtime things that won't show up just by doing a build.

But, the library names aren't the cause of your initial problem. That is failing to find the header files. But apparently you can build now? So this must have got fixed some other way.

**Comment by ikatza** [comment]
Yeah, you are right. Got it to work because I'm locally building `sbnanaobj` not because I renamed them.

Better to have a separate issue: https://github.com/SBNSoftware/sbncode/issues/84

**Comment by cjbackhouse** [comment]
Merged this since both Iker and Gray ran into it, so it definitely needed fixing.

**Pull request merged**
