### PR TITLE
feature/ensemblespectrum

### PR DESCRIPTION
**Pull request by cjbackhouse**

### CODE REVIEW

**Comment by brucehoward-physics** [comment]
Having trouble running the example script with ICARUS samples. I'm not sure exactly what's going wrong but can take a look tomorrow.

I can't comment on the merits of one quantile-finding algorithm over another considering as Chris notes that there are multiple options. But, I think there is a small issue in the algorithm currently coded. If `frac` > N/(N+1), then I think it will try to look at `xs[N]`, no? (which isn't correct)

Some other comments:
* It seems like in `EnsembleSpectrum` the `*` and `/` operators go with `EnsembleRatio`s and not other `EnsembleSpectra`. Is this purposeful? I guess this makes sense.
* In `DrawErrorBand`, I notice it's using bins+2. I think this gets the underflow and overflow? If I'm right, then when it's re-scaling y, will it change the scale to match the underflow/overflow if one of those is max? Sorry if I'm misreading...

**Comment by cjbackhouse** [comment]
Thanks for the thorough review! I think you're right about both issues. I pushed simple fixes.

Indeed you can only multiply a spectrum by a ratio. The Ensemble implementation is parallel to what exists for regular spectra/ratios. A spectrum is conceptually a rate: events/pot, while a ratio is dimensionless, so spectrum*spectrum doesn't make sense - you get events^2/pot^2. Spectrum divided by Spectrum does make sense, but that is defined in the Ratio header.

For Icarus files, let me know if you can't easily figure it out, and point me to the files you're using. For SBND I actually had to hack some stuff about the primary muon out of the selection. I guess things have changed since the PAC macros already?

**Comment by brucehoward-physics** [comment]
Tinkered and got the test macro to run on a NuMI CAF file with truth-level cuts (NumuCC and NC) and produce some plots.

**Review by brucehoward-physics — APPROVED** [review]
Had a few algorithm comments that were addressed, and I got the test macro to run also in ICARUS after tinkering a bit.

**Pull request merged**
