### PR TITLE
Use $SAM_EXPERIMENT environment variable rather than $EXPERIMENT for SAM purposes

### PR DESCRIPTION
**Pull request by cjbackhouse**
We expect $SAM_EXPERIMENT to be 'sbn' soon, while $EXPERIMENT will presumably still be 'sbnd'/'icarus'

### CODE REVIEW

**Comment by etyley** [comment]
I tried testing this but it still seems to be using the `EXPERIMENT` rather than the `SAM_EXPERIMENT` for the query. I am not familiar enough with IFDH to be able to debug any further than that sorry.

**Comment by cjbackhouse** [comment]
Yeah, I missed some critical spots, and it turns out ifdh is semi-hardcoded to use `$EXPERIMENT`. Shouldn't be unresolvable though.

**Comment by cjbackhouse** [comment]
@etyley I think this should work now?

**Review by etyley — APPROVED** [review]
This works for me now

**Pull request merged**
