### PR TITLE
Implement NuMI flux systs using external histogram file

### PR DESCRIPTION
**Pull request by cjbackhouse**
The histogram file needs to be located somewhere official, probably `sbndata`? That is the main thing preventing merging this.

### CODE REVIEW

**Comment by wesketchum** [comment]
@cjbackhouse @miquelnebot is this something that needs to be added to sbndata?

**Comment by cjbackhouse** [comment]
That seems by far the most natural to me. The file is currently found in https://gitlab.com/apwood93/numi-at-icarus-flux-systematics.git
You should probably coordinate with Anthony Wood and Dan Cherdack about whether they're happy to have what's there now packaged, and what the system for asking for updates in future will be.

**Comment by cjbackhouse** [comment]
Where is `sbndata` installed? `ups` doesn't seem to know about it, even after I set up sbndcode.

**Comment by cjbackhouse** [comment]
huh, I see it at `/cvmfs/sbn.opensciencegrid.org/products/sbn/sbndata/`, which `ups list` claims it's searching...

**Comment by jzennamo** [comment]
@jacoblarkin and @etyley any news on reviewing this PR before Friday? Thanks!

**Review by jacoblarkin — APPROVED** [review]
Looks good. I also tested this by making oscillation contours and it seems to work.

**Pull request merged**
