### PR TITLE
Feature/jskim multisigma

### PR DESCRIPTION
**Pull request by jedori0228**
With https://github.com/SBNSoftware/sbncode/pull/233, the structure of weight values saved in the (flat)caf is changed.
This PR will handle the changes in the sbncode, and also an example script `sbnana/CAFAna/test/test_GENIESyst.C` is added.

### CODE REVIEW

**Comment by cjbackhouse** [comment]
Thanks for this! I have a few minor comments, but maybe it's better to wait until there is a large-ish sample of files produced this way? Otherwise, we just break the ability to use the old files, right?

**Comment by jedori0228** [comment]
https://github.com/SBNSoftware/sbnanaobj/pull/45 should be also merged toghether

**Comment by jedori0228** [comment]
> Thanks for this! I have a few minor comments, but maybe it's better to wait until there is a large-ish sample of files produced this way? Otherwise, we just break the ability to use the old files, right?

The flatcaf files I used in `sbnana/CAFAna/test/test_GENIESyst.C` (`/pnfs/icarus/scratch/users/jskim/mc/NUMI_Nu_Cosmics/flatcaf/v09_42_00/MultiSigmaAdded/*.root`) took the all available reco2 files of `icarusprod_2021C_NUMI_Nu_Cosmics_v09_37_01_02p01_reco2` as input (including few failure in grid jobs).

**Comment by jedori0228** [comment]
I close this PR, to rebase it on release/SBN2021C rather than develop.

**Pull request closed without merging**
